services:

  postgres:
    image: 'postgres:18.3'
    container_name: 'postgres'
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=moviedb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "moviedb"]
